name: STILLNESS
favicon: null
layout_spectrum: 0.18252
typography_spectrum: 0.38078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c1a96b'
    - '#4b3f25'
    - '#66563c'
    - '#261b09'
  brandStrength: 1
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
